version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant-management
    ports:
      - '5432:5432'
    volumes: 
      - ./Docker/postgres:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=root@postgres.com
        - PGADMIN_DEFAULT_PASSWORD=root
    ports:
        - '8080:80'